[build]
    base = "/"
    publish = "build/"
    command = "yarn build"


[build.environment] 
    REACT_APP_FINHUB_API_KEY = "bue62i748v6vkac99otg"
    REACT_APP_API_KEY = "AC0UPC4CHJBEZAKXATUXTRZDHLLRCCJL"
    REACT_APP_REFRESH_TOKEN = "EsOV6cwno95gvdgN1uAl6ezU1qHNLDrW1Tt3NFy41ERAyS7MOGqIIn34+Ik40s3Q+f8UhCge758bUtBumJX8oUQ6nsN3QrRYVVsjCZSBcpz/sMwTpt49frSxXwz/a0KvK+Z25UL5CFgOE0mP4vDNx7ZtVnQyjVm3JfNWbTho2wC9rtJIiNbcD+7CBCOHulBijWyGtbu8SR2pRPNw9vNhFt0EtZSRA6xBZ5jSbJdmLRHk2eh70sHEwqaFbROKZKOjWv+ecJ697gC/ZnosWACsAqsGBr9wZcSzfdZf9gzHCUcXQMGAatXCYGEVy0yF5ROpZL9nk/eAIuhEEtoIptyeoomHHMh6M6KaIO3R1dPycv2xLpsZchw9nhLPWWuKxeHXLsZnT82eXSJNhfMFph1hDBOn8boZBGNPb7JmusqoZVowIaSukNmfC4tDDFx100MQuG4LYrgoVi/JHHvlpTjVP8gJO+0Nxgx2TJgCQrnvAyrxqsNq9yUKPM0iZL2zECru/yKGt5oazE1+snDy35h9cGOiGexdEkXEyrAgNB75XXY75fY/ZBATQw9A7TYi4CR/slJtxpTxe95qsAEmZQbfMLYb+GzXwrji+T578tEvn20gqBzlrSSsleX5k2IYRI/ulvbnVOEdWKKAF+5fw8oz5gUlUnLA51pCc2LQkyhNQtSAlAzmPU/0AvwuxqRpe9v8qqr0KLox+Gh2vSacO6xRNKNRloa4BtZ3f915xxaGppA/ACYnjTo4xwaWCdcdRRExBkkeXGckRnLixcDokjGo9qlDmuKYIT3ZrP0WWutb6+/fuMt6Sadfbnp06txYt5mseNhPWSBewUkdHH4ZtGozYLsbkU8seTZDPUqxHKCrzm3kqgjXe5JAFuX2Vo31DckajLfM69qvpeo=212FD3x19z9sWBHDJACbC00B75E" 